version: "3.0"

services:
  tomcat:
    container_name: tomcat
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    volumes:
      - "./workspace:/home/jenkins"
      - "./webapps:/usr/local/tomcat/webapps"
    ports:
      - "8888:8080"
      - "2222:22"
    entrypoint: |
      bash -c 'cp -a webapps.dist/manager webapps/; exec catalina.sh run'
    networks:
      slave:
        ipv4_address: 172.20.0.3
  dind:
    container_name: dind
    build:
      dockerfile: Dockerfile
      context: ./docker
    restart: always
    privileged: true
    volumes:
      - "./docker:/home/docker"
    ports:
      - "2223:22"
    networks:
      slave:
        ipv4_address: 172.20.0.4

networks:
  slave:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
